set(_CATKIN_CURRENT_PACKAGE "wheel")
set(wheel_VERSION "0.0.0")
set(wheel_MAINTAINER "root <root@todo.todo>")
set(wheel_PACKAGE_FORMAT "1")
set(wheel_BUILD_DEPENDS "message_generation" "rospy")
set(wheel_BUILD_EXPORT_DEPENDS "rospy")
set(wheel_BUILDTOOL_DEPENDS "catkin")
set(wheel_BUILDTOOL_EXPORT_DEPENDS )
set(wheel_EXEC_DEPENDS "rospy")
set(wheel_RUN_DEPENDS "rospy")
set(wheel_TEST_DEPENDS )
set(wheel_DOC_DEPENDS )
set(wheel_URL_WEBSITE "")
set(wheel_URL_BUGTRACKER "")
set(wheel_URL_REPOSITORY "")
set(wheel_DEPRECATED "")