set(_CATKIN_CURRENT_PACKAGE "keyboard_cont")
set(keyboard_cont_VERSION "0.0.0")
set(keyboard_cont_MAINTAINER "mangokid <mangokid@todo.todo>")
set(keyboard_cont_PACKAGE_FORMAT "2")
set(keyboard_cont_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "sensor_msgs")
set(keyboard_cont_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs" "rospy" "std_msgs" "sensor_msgs")
set(keyboard_cont_BUILDTOOL_DEPENDS "catkin")
set(keyboard_cont_BUILDTOOL_EXPORT_DEPENDS )
set(keyboard_cont_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "sensor_msgs")
set(keyboard_cont_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "sensor_msgs")
set(keyboard_cont_TEST_DEPENDS )
set(keyboard_cont_DOC_DEPENDS )
set(keyboard_cont_URL_WEBSITE "")
set(keyboard_cont_URL_BUGTRACKER "")
set(keyboard_cont_URL_REPOSITORY "")
set(keyboard_cont_DEPRECATED "")