set(_CATKIN_CURRENT_PACKAGE "joy_cmd")
set(joy_cmd_VERSION "0.0.0")
set(joy_cmd_MAINTAINER "mangokid <mangokid@todo.todo>")
set(joy_cmd_PACKAGE_FORMAT "2")
set(joy_cmd_BUILD_DEPENDS "geometry_msgs" "rospy" "sensor_msgs")
set(joy_cmd_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy" "sensor_msgs")
set(joy_cmd_BUILDTOOL_DEPENDS "catkin")
set(joy_cmd_BUILDTOOL_EXPORT_DEPENDS )
set(joy_cmd_EXEC_DEPENDS "geometry_msgs" "rospy" "sensor_msgs")
set(joy_cmd_RUN_DEPENDS "geometry_msgs" "rospy" "sensor_msgs")
set(joy_cmd_TEST_DEPENDS )
set(joy_cmd_DOC_DEPENDS )
set(joy_cmd_URL_WEBSITE "")
set(joy_cmd_URL_BUGTRACKER "")
set(joy_cmd_URL_REPOSITORY "")
set(joy_cmd_DEPRECATED "")