set(_CATKIN_CURRENT_PACKAGE "system_control")
set(system_control_VERSION "0.0.0")
set(system_control_MAINTAINER "mangokid <mangokid@todo.todo>")
set(system_control_PACKAGE_FORMAT "2")
set(system_control_BUILD_DEPENDS "rospy" "std_msgs")
set(system_control_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(system_control_BUILDTOOL_DEPENDS "catkin")
set(system_control_BUILDTOOL_EXPORT_DEPENDS )
set(system_control_EXEC_DEPENDS "rospy" "std_msgs")
set(system_control_RUN_DEPENDS "rospy" "std_msgs")
set(system_control_TEST_DEPENDS )
set(system_control_DOC_DEPENDS )
set(system_control_URL_WEBSITE "")
set(system_control_URL_BUGTRACKER "")
set(system_control_URL_REPOSITORY "")
set(system_control_DEPRECATED "")